spring.application.name=cricket

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cricketdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=archana

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
